### PR TITLE
Add support for Eltako temperature/humidity sensor

### PR DESCRIPTION
**Pull request by smeyersdev**
Hello,

I have added support for an Eltako temperature/humidity sensor, I have bought some days ago. Its using EPP A5:04:02. The only difference between the existing classes for A5:04:01 and A5:04:02 is the temperature range. 

The new code was tested with an openhab instance at my home and it worked great.

Best regards,

Stephan Meyer

### CODE REVIEW

**Comment by maggu2810** [comment]
Seems to be good. Will have a look to it later. Perhabs create a abstract remote device A504. But have to inspect the current code base.

**Comment by smeyersdev** [comment]
Hi Markus,

I did now some code cleaning and use an abstract class for both temperature/humidity sensors.

Best regards,

Stephan Meyer

**Comment by maggu2810** [comment]
Hello!

I will try to find some time to look at it.
Sorry, but I am very busy at the moment.

Thanks for you work.

Best regards,
Markus

2015-01-28 12:48 GMT+01:00 Stephan Meyer <notifications@github.com>:

**Comment by maggu2810** [comment]
Sorry, for the late merge.
It looks fine. Thank you

**Pull request merged**
